services:
  docmost:
    image: docmost-gevekom:0.25.3-nozip
    depends_on:
      - db
      - redis
    environment:
      APP_URL: 'http://localhost:3000'
      APP_SECRET: 'cca9eb0663c911f09118745d2263e9e9'
      DATABASE_URL: 'postgresql://docmost:customPW@db:5432/docmost?schema=public'
      REDIS_URL: 'redis://redis:6379'
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - docmost:/app/data/storage

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: customPW
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2-alpine
    command: ["redis-server", "--appendonly", "yes", "--maxmemory-policy", "noeviction"]
#    restart: unless-stopped
    volumes:
      - docmost_redis_data:/data
    ports:
      - "6379:6379"

volumes:
  docmost:
  db_data:
  docmost_redis_data:
